import { writable } from "svelte/store";
export const works=writable([
    {portada: 'sista',
    main:'sista',
    titulo:'Sista',
    sub:'Diseño Web',
    hashtags:['Rediseño', 'Ux', 'Desarrollo'],
    a:'sista',
    imgStyle:'position:absolute; right:0; top:20%; width:50vw; z-index:-1',
    divStyle:'margin-top:50vh; margin-left:4em; width:30vw'
    },
    {portada: 'oddel',
    main:'oddel',
    titulo:'Oddel',
    sub:'Diseño Web',
    hashtags:['web', 'Ux', 'Desarrollo'],
    a:'oddel',
    imgStyle:'position:absolute; right:0; bottom:0; width:50vw'
    },
    {portada: 'trapitos',
    main:'trapitos',
    titulo:'Trapitos al Sol',
    sub:'Identidad y flyers',
    hashtags:['Identidad', 'Proyecto personal', 'Espectáculo'],
    a: 'trapitos-al-sol',
    imgStyle:'position:absolute; left:0; top:0; width:30vw; z-index:-1',
    divStyle:'margin-left:40vw; margin-top:6em; width:40vw'
    },
    {portada: 'santi',
    main:'ss',
    titulo:'Santiago Sosa',
    sub:'Diseño web',
    hashtags:['Ux', 'Web'],
    a:'santiago-sosa',
    imgStyle:'position:absolute; right:0; top:10%; width:60vw; z-index:-1'
    },
    {portada: 'santi_d',
    main:'sd',
    titulo:'Santiago Dopazo',
    sub:'Diseño web',
    hashtags:['Ux', 'Web'],
    a:'santiago-dopazo',
    imgStyle:'position:absolute; left:0; top:0; width:30vw; z-index:-1',
    divStyle:'margin-left:40vw; margin-top:6em; width:40vw',
    },
    {portada: 'emanaras',
    main:'emanaras',
    titulo:'Emanaras',
    sub:'Logo e Identidad',
    hashtags:['Identidad', 'Logo', 'Branding'],
    a:'emanaras',
    imgStyle:'position:absolute; left:0; top:0; width:50vw; z-index:-1',
    divStyle:'margin-left:40vw; margin-top:6em; width:40vw',
    },
]);
export const actualPage=writable();